AWSTemplateFormatVersion: "2025-09-06"
Description: "Create a subnet in a chosen VPC"

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: "Select the VPC where the subnet will be created (choose the default VPC if needed)."

  SubnetCidrBlock:
    Type: String
    Default: 172.31.100.0/24
    AllowedPattern: "(\\d{1,3}\\.){3}\\d{1,3}/(\\d{1,2})"
    Description: "CIDR block for the new subnet (must be inside the VPC CIDR and not overlap with existing subnets). Example: 172.31.100.0/24"

  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: "Select the Availability Zone for the subnet."

  SubnetName:
    Type: String
    Default: devops-subnet
    Description: "Name tag for the new subnet."

Resources:
  DevopsSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref SubnetCidrBlock
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: !Ref SubnetName

Outputs:
  SubnetId:
    Description: "The ID of the newly created subnet"
    Value: !Ref DevopsSubnet

  SubnetCidr:
    Description: "The CIDR block of the subnet"
    Value: !Ref SubnetCidrBlock
